-- IQ-0 foundations: storage for the intelligence engine. Requires 0033.
-- hive reviews/iq-0 DESIGN.md §2 + DESIGN-v2-DELTA.md §2; schema in
-- src/db/schema/iq.ts. Recovery: docs/MIGRATION-RECOVERY.md and
-- supabase/rollback/0034_iq_foundations.down.sql.
--
-- Generated by drizzle-kit, then three hand edits at the end, which drizzle
-- cannot express: iq_insights_superseded_by_fk is DEFERRABLE (a supersede
-- marks the old row before inserting the new one), the triggers that freeze
-- a referenced insight and stamp iq_actions.status_changed_at, and RLS +
-- grants.
--
-- Journal `when` is set by hand to 1789800000000: drizzle-kit stamped the
-- wall clock, which is below 0033's 1789700000000, and `db:migrate` skips any
-- entry not newer than the last applied one.
CREATE TABLE "iq_actions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"location_id" uuid,
	"recommendation_id" uuid,
	"action_kind" text NOT NULL,
	"tier" text NOT NULL,
	"mode" text NOT NULL,
	"status" text NOT NULL,
	"status_changed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"params" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"params_hash" text NOT NULL,
	"idempotency_key" text NOT NULL,
	"origin" text NOT NULL,
	"requested_by" uuid,
	"auto_policy_id" uuid,
	"auto_policy_version" integer,
	"approved_by" uuid,
	"approved_at" timestamp with time zone,
	"approval_expires_at" timestamp with time zone,
	"execute_by" timestamp with time zone,
	"decided_by" uuid,
	"decided_at" timestamp with time zone,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"attempt" integer DEFAULT 0 NOT NULL,
	"lease_owner" uuid,
	"lease_expires_at" timestamp with time zone,
	"target_entity" text,
	"target_id" text,
	"before" jsonb,
	"after" jsonb,
	"undo_kind" text DEFAULT 'NONE' NOT NULL,
	"undo_params" jsonb,
	"undone_at" timestamp with time zone,
	"undone_by" uuid,
	"error_code" text,
	"error_message" text,
	"audit_log_id" uuid,
	"job_run_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "iq_actions_idempotency_unique" UNIQUE("org_id","idempotency_key"),
	CONSTRAINT "iq_actions_tier_check" CHECK ("iq_actions"."tier" IN ('A0', 'A1', 'A2', 'A3')),
	CONSTRAINT "iq_actions_mode_check" CHECK ("iq_actions"."mode" IN ('AUTO', 'APPROVAL', 'HANDOFF')),
	CONSTRAINT "iq_actions_status_check" CHECK ("iq_actions"."status" IN ('QUEUED', 'PENDING_APPROVAL', 'APPROVED', 'EXECUTING', 'SUCCEEDED', 'FAILED', 'REJECTED', 'EXPIRED', 'SUPERSEDED', 'CANCELLED', 'UNDONE', 'HANDOFF', 'UNDOING', 'UNDO_FAILED')),
	CONSTRAINT "iq_actions_kind_tier_check" CHECK ("iq_actions"."tier" = 'A3' OR ("iq_actions"."action_kind", "iq_actions"."tier") IN (('brief.publish', 'A0'), ('detection.publish', 'A0'), ('forecast.publish', 'A0'), ('reconciliation.report', 'A0'), ('purchase_order.create_draft', 'A1'), ('inventory.flag_recount', 'A1'), ('prep_list.prefill', 'A1'), ('task.open_internal', 'A1'), ('menu.mark_86', 'A2'), ('customer.winback_message', 'A2'))),
	CONSTRAINT "iq_actions_tier_mode_check" CHECK (("iq_actions"."tier" = 'A0' AND "iq_actions"."mode" = 'AUTO')
          OR ("iq_actions"."tier" = 'A1' AND "iq_actions"."mode" IN ('AUTO', 'APPROVAL'))
          OR ("iq_actions"."tier" = 'A2' AND "iq_actions"."mode" = 'APPROVAL')
          OR ("iq_actions"."tier" = 'A3' AND "iq_actions"."mode" = 'HANDOFF')),
	CONSTRAINT "iq_actions_mode_status_check" CHECK (("iq_actions"."mode" = 'AUTO' AND "iq_actions"."status" IN ('QUEUED', 'EXECUTING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'UNDOING', 'UNDONE', 'UNDO_FAILED'))
          OR ("iq_actions"."mode" = 'APPROVAL' AND "iq_actions"."status" IN ('PENDING_APPROVAL', 'APPROVED', 'EXECUTING', 'SUCCEEDED', 'FAILED', 'REJECTED', 'EXPIRED', 'SUPERSEDED', 'CANCELLED', 'UNDOING', 'UNDONE', 'UNDO_FAILED'))
          OR ("iq_actions"."mode" = 'HANDOFF' AND "iq_actions"."status" IN ('HANDOFF', 'CANCELLED', 'EXPIRED', 'SUPERSEDED'))),
	CONSTRAINT "iq_actions_approval_expiry_check" CHECK ("iq_actions"."mode" <> 'APPROVAL' OR "iq_actions"."approval_expires_at" IS NOT NULL),
	CONSTRAINT "iq_actions_approved_by_check" CHECK ("iq_actions"."mode" <> 'APPROVAL' OR "iq_actions"."status" NOT IN ('APPROVED', 'EXECUTING', 'SUCCEEDED', 'FAILED', 'UNDOING', 'UNDONE', 'UNDO_FAILED')
          OR ("iq_actions"."approved_by" IS NOT NULL AND "iq_actions"."approved_at" IS NOT NULL)),
	CONSTRAINT "iq_actions_execute_by_check" CHECK ("iq_actions"."status" <> 'APPROVED' OR "iq_actions"."execute_by" IS NOT NULL),
	CONSTRAINT "iq_actions_lease_check" CHECK (("iq_actions"."status" IN ('EXECUTING', 'UNDOING')) = ("iq_actions"."lease_owner" IS NOT NULL AND "iq_actions"."lease_expires_at" IS NOT NULL)),
	CONSTRAINT "iq_actions_auto_policy_check" CHECK (CASE WHEN "iq_actions"."tier" = 'A1' AND "iq_actions"."mode" = 'AUTO'
            THEN "iq_actions"."auto_policy_id" IS NOT NULL AND "iq_actions"."auto_policy_version" IS NOT NULL
            ELSE "iq_actions"."auto_policy_id" IS NULL AND "iq_actions"."auto_policy_version" IS NULL END),
	CONSTRAINT "iq_actions_params_hash_check" CHECK ("iq_actions"."params_hash" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "iq_actions_attempt_check" CHECK ("iq_actions"."attempt" >= 0),
	CONSTRAINT "iq_actions_undo_kind_check" CHECK ("iq_actions"."undo_kind" IN ('NONE', 'REVERT', 'COMPENSATING')),
	CONSTRAINT "iq_actions_undone_check" CHECK (("iq_actions"."status" = 'UNDONE') = ("iq_actions"."undone_at" IS NOT NULL)),
	CONSTRAINT "iq_actions_error_message_check" CHECK (char_length("iq_actions"."error_message") <= 500)
);
--> statement-breakpoint
CREATE TABLE "iq_auto_policies" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"action_kind" text NOT NULL,
	"location_id" uuid,
	"enabled" boolean DEFAULT false NOT NULL,
	"limits" jsonb NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"set_by" uuid NOT NULL,
	"set_at" timestamp with time zone DEFAULT now() NOT NULL,
	"reason" text NOT NULL,
	"audit_log_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "iq_auto_policies_scope_unique" UNIQUE NULLS NOT DISTINCT("org_id","action_kind","location_id"),
	CONSTRAINT "iq_auto_policies_id_org_unique" UNIQUE("id","org_id"),
	CONSTRAINT "iq_auto_policies_kind_check" CHECK ("iq_auto_policies"."action_kind" IN ('purchase_order.create_draft', 'inventory.flag_recount', 'prep_list.prefill', 'task.open_internal')),
	CONSTRAINT "iq_auto_policies_version_check" CHECK ("iq_auto_policies"."version" >= 1),
	CONSTRAINT "iq_auto_policies_limits_check" CHECK (CASE WHEN jsonb_typeof("iq_auto_policies"."limits") = 'object'
            AND ("iq_auto_policies"."limits" - 'maxPerDay') = '{}'::jsonb
            AND jsonb_typeof("iq_auto_policies"."limits" -> 'maxPerDay') = 'number'
          THEN ("iq_auto_policies"."limits" ->> 'maxPerDay')::numeric BETWEEN 1 AND 50
            AND ("iq_auto_policies"."limits" ->> 'maxPerDay')::numeric = trunc(("iq_auto_policies"."limits" ->> 'maxPerDay')::numeric)
          ELSE false END),
	CONSTRAINT "iq_auto_policies_reason_check" CHECK (char_length("iq_auto_policies"."reason") BETWEEN 1 AND 500)
);
--> statement-breakpoint
CREATE TABLE "iq_forecasts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"location_id" uuid,
	"insight_id" uuid,
	"target_kind" text NOT NULL,
	"target_ref" text NOT NULL,
	"business_date" date NOT NULL,
	"daypart" text DEFAULT 'ALL' NOT NULL,
	"unit" text NOT NULL,
	"p10" bigint NOT NULL,
	"p50" bigint NOT NULL,
	"p90" bigint NOT NULL,
	"model_id" text NOT NULL,
	"model_version" text NOT NULL,
	"is_naive_fallback" boolean DEFAULT false NOT NULL,
	"issued_for" date NOT NULL,
	"horizon_days" integer NOT NULL,
	"backtest_metric" text NOT NULL,
	"model_error_bps" integer NOT NULL,
	"naive_error_bps" integer NOT NULL,
	"backtest_window_days" integer NOT NULL,
	"backtest_provenance" text NOT NULL,
	"job_run_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "iq_forecasts_target_unique" UNIQUE NULLS NOT DISTINCT("org_id","location_id","target_kind","target_ref","business_date","daypart","model_id","model_version","issued_for"),
	CONSTRAINT "iq_forecasts_target_kind_check" CHECK ("iq_forecasts"."target_kind" IN ('ITEM', 'INGREDIENT', 'ORDERS', 'REVENUE')),
	CONSTRAINT "iq_forecasts_unit_check" CHECK ("iq_forecasts"."unit" IN ('paise', 'count', 'bps', 'grams', 'ml', 'pieces', 'seconds')),
	CONSTRAINT "iq_forecasts_interval_check" CHECK (0 <= "iq_forecasts"."p10" AND "iq_forecasts"."p10" <= "iq_forecasts"."p50" AND "iq_forecasts"."p50" <= "iq_forecasts"."p90"),
	CONSTRAINT "iq_forecasts_horizon_check" CHECK ("iq_forecasts"."horizon_days" >= 0),
	CONSTRAINT "iq_forecasts_backtest_metric_check" CHECK ("iq_forecasts"."backtest_metric" IN ('WAPE', 'MAE')),
	CONSTRAINT "iq_forecasts_backtest_provenance_check" CHECK ("iq_forecasts"."backtest_provenance" IN ('LOCAL_SYNTHETIC', 'APPROVED_EXPORT', 'PRODUCTION_JOB')),
	CONSTRAINT "iq_forecasts_backtest_numbers_check" CHECK ("iq_forecasts"."model_error_bps" >= 0 AND "iq_forecasts"."naive_error_bps" >= 0 AND "iq_forecasts"."backtest_window_days" >= 1)
);
--> statement-breakpoint
CREATE TABLE "iq_insights" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"location_id" uuid,
	"claim_type" text NOT NULL,
	"schema_version" integer DEFAULT 1 NOT NULL,
	"producer" text NOT NULL,
	"subject_kind" text NOT NULL,
	"subject_ref" text NOT NULL,
	"period_start" timestamp with time zone NOT NULL,
	"period_end" timestamp with time zone NOT NULL,
	"dedupe_key" text NOT NULL,
	"severity" smallint,
	"status" text DEFAULT 'ACTIVE' NOT NULL,
	"payload" jsonb NOT NULL,
	"evidence" jsonb NOT NULL,
	"trust_state" text DEFAULT 'NOT_MEASURED' NOT NULL,
	"trust_score" integer,
	"trust_as_of" timestamp with time zone,
	"job_run_id" uuid,
	"job_attempt" integer,
	"code_version" text NOT NULL,
	"content_hash" text NOT NULL,
	"supersedes" uuid,
	"superseded_by" uuid,
	"referenced_at" timestamp with time zone,
	"expires_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "iq_insights_id_org_unique" UNIQUE("id","org_id"),
	CONSTRAINT "iq_insights_claim_type_check" CHECK ("iq_insights"."claim_type" IN ('FACT', 'DETECTION', 'FORECAST', 'EXPLANATION', 'RECOMMENDATION', 'AUTOMATION')),
	CONSTRAINT "iq_insights_status_check" CHECK ("iq_insights"."status" IN ('ACTIVE', 'SUPERSEDED', 'EXPIRED', 'RETRACTED')),
	CONSTRAINT "iq_insights_subject_kind_check" CHECK ("iq_insights"."subject_kind" IN ('ORG', 'LOCATION', 'PRODUCT', 'MODIFIER', 'INGREDIENT', 'RECIPE', 'SUPPLIER', 'CHANNEL', 'DAYPART', 'METRIC', 'JOB')),
	CONSTRAINT "iq_insights_trust_state_check" CHECK ("iq_insights"."trust_state" IN ('MEASURED', 'NOT_MEASURED', 'INSUFFICIENT_DATA')),
	CONSTRAINT "iq_insights_trust_score_check" CHECK (("iq_insights"."trust_state" = 'MEASURED') = ("iq_insights"."trust_score" IS NOT NULL AND "iq_insights"."trust_as_of" IS NOT NULL) AND ("iq_insights"."trust_score" IS NULL OR "iq_insights"."trust_score" BETWEEN 0 AND 100)),
	CONSTRAINT "iq_insights_schema_version_check" CHECK ("iq_insights"."schema_version" >= 1),
	CONSTRAINT "iq_insights_severity_check" CHECK ("iq_insights"."severity" IS NULL OR "iq_insights"."severity" BETWEEN 1 AND 3),
	CONSTRAINT "iq_insights_period_check" CHECK ("iq_insights"."period_end" >= "iq_insights"."period_start"),
	CONSTRAINT "iq_insights_content_hash_check" CHECK ("iq_insights"."content_hash" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "iq_insights_payload_object_check" CHECK (jsonb_typeof("iq_insights"."payload") = 'object'),
	CONSTRAINT "iq_insights_evidence_check" CHECK (jsonb_typeof("iq_insights"."evidence") = 'array' AND jsonb_array_length("iq_insights"."evidence") >= 1),
	CONSTRAINT "iq_insights_no_bare_value_check" CHECK ("iq_insights"."claim_type" IN ('FACT', 'DETECTION') OR NOT ("iq_insights"."payload" ? 'value')),
	CONSTRAINT "iq_insights_forecast_interval_check" CHECK ("iq_insights"."claim_type" <> 'FORECAST' OR "iq_insights"."payload" ? 'interval'),
	CONSTRAINT "iq_insights_recommendation_expiry_check" CHECK ("iq_insights"."claim_type" <> 'RECOMMENDATION' OR "iq_insights"."expires_at" IS NOT NULL),
	CONSTRAINT "iq_insights_supersede_check" CHECK (("iq_insights"."supersedes" IS NULL OR "iq_insights"."supersedes" <> "iq_insights"."id") AND ("iq_insights"."superseded_by" IS NULL OR ("iq_insights"."superseded_by" <> "iq_insights"."id" AND "iq_insights"."status" = 'SUPERSEDED')))
);
--> statement-breakpoint
CREATE TABLE "iq_job_runs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"job" text NOT NULL,
	"period_key" text NOT NULL,
	"status" text DEFAULT 'RUNNING' NOT NULL,
	"trigger" text NOT NULL,
	"attempt" integer DEFAULT 1 NOT NULL,
	"lease_owner" uuid NOT NULL,
	"lease_expires_at" timestamp with time zone NOT NULL,
	"deadline_at" timestamp with time zone NOT NULL,
	"heartbeat_at" timestamp with time zone,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"finished_at" timestamp with time zone,
	"duration_ms" integer,
	"rows_written" integer DEFAULT 0 NOT NULL,
	"summary" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"error_code" text,
	"error_message" text,
	"code_version" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "iq_job_runs_job_org_period_unique" UNIQUE("job","org_id","period_key"),
	CONSTRAINT "iq_job_runs_status_check" CHECK ("iq_job_runs"."status" IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED')),
	CONSTRAINT "iq_job_runs_trigger_check" CHECK ("iq_job_runs"."trigger" IN ('TIMER', 'MANUAL', 'CATCHUP')),
	CONSTRAINT "iq_job_runs_attempt_check" CHECK ("iq_job_runs"."attempt" >= 1),
	CONSTRAINT "iq_job_runs_counts_check" CHECK ("iq_job_runs"."rows_written" >= 0 AND ("iq_job_runs"."duration_ms" IS NULL OR "iq_job_runs"."duration_ms" >= 0)),
	CONSTRAINT "iq_job_runs_summary_check" CHECK (jsonb_typeof("iq_job_runs"."summary") = 'object'),
	CONSTRAINT "iq_job_runs_error_message_check" CHECK (char_length("iq_job_runs"."error_message") <= 500)
);
--> statement-breakpoint
CREATE TABLE "iq_outcomes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"subject_kind" text NOT NULL,
	"subject_id" uuid NOT NULL,
	"metric_id" text NOT NULL,
	"window_start" timestamp with time zone NOT NULL,
	"window_end" timestamp with time zone NOT NULL,
	"unit" text NOT NULL,
	"expected_low" bigint NOT NULL,
	"expected_high" bigint NOT NULL,
	"actual" bigint,
	"verdict" text NOT NULL,
	"trust_score_at_measure" integer,
	"job_run_id" uuid,
	"measured_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "iq_outcomes_window_unique" UNIQUE("org_id","subject_kind","subject_id","metric_id","window_end"),
	CONSTRAINT "iq_outcomes_subject_kind_check" CHECK ("iq_outcomes"."subject_kind" IN ('ACTION', 'RECOMMENDATION', 'FORECAST')),
	CONSTRAINT "iq_outcomes_unit_check" CHECK ("iq_outcomes"."unit" IN ('paise', 'count', 'bps', 'grams', 'ml', 'pieces', 'seconds')),
	CONSTRAINT "iq_outcomes_verdict_check" CHECK ("iq_outcomes"."verdict" IN ('WITHIN', 'BETTER', 'WORSE', 'INCONCLUSIVE', 'DATA_MISSING')),
	CONSTRAINT "iq_outcomes_window_check" CHECK ("iq_outcomes"."window_end" >= "iq_outcomes"."window_start"),
	CONSTRAINT "iq_outcomes_expected_check" CHECK ("iq_outcomes"."expected_low" <= "iq_outcomes"."expected_high"),
	CONSTRAINT "iq_outcomes_actual_check" CHECK (("iq_outcomes"."verdict" = 'DATA_MISSING') = ("iq_outcomes"."actual" IS NULL)),
	CONSTRAINT "iq_outcomes_trust_score_check" CHECK ("iq_outcomes"."trust_score_at_measure" IS NULL OR "iq_outcomes"."trust_score_at_measure" BETWEEN 0 AND 100)
);
--> statement-breakpoint
CREATE TABLE "iq_recommendations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"location_id" uuid,
	"insight_id" uuid NOT NULL,
	"action_kind" text NOT NULL,
	"tier" text NOT NULL,
	"params" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"params_hash" text NOT NULL,
	"impact_unit" text NOT NULL,
	"impact_low" bigint NOT NULL,
	"impact_high" bigint NOT NULL,
	"confidence" text NOT NULL,
	"assumptions" jsonb NOT NULL,
	"status" text DEFAULT 'PROPOSED' NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"decided_by_user_id" uuid,
	"decided_at" timestamp with time zone,
	"decision_reason" text,
	"dedupe_key" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "iq_recommendations_insight_unique" UNIQUE("insight_id"),
	CONSTRAINT "iq_recommendations_id_org_unique" UNIQUE("id","org_id"),
	CONSTRAINT "iq_recommendations_tier_check" CHECK ("iq_recommendations"."tier" IN ('A0', 'A1', 'A2', 'A3')),
	CONSTRAINT "iq_recommendations_kind_tier_check" CHECK ("iq_recommendations"."tier" = 'A3' OR ("iq_recommendations"."action_kind", "iq_recommendations"."tier") IN (('brief.publish', 'A0'), ('detection.publish', 'A0'), ('forecast.publish', 'A0'), ('reconciliation.report', 'A0'), ('purchase_order.create_draft', 'A1'), ('inventory.flag_recount', 'A1'), ('prep_list.prefill', 'A1'), ('task.open_internal', 'A1'), ('menu.mark_86', 'A2'), ('customer.winback_message', 'A2'))),
	CONSTRAINT "iq_recommendations_params_hash_check" CHECK ("iq_recommendations"."params_hash" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "iq_recommendations_params_object_check" CHECK (jsonb_typeof("iq_recommendations"."params") = 'object'),
	CONSTRAINT "iq_recommendations_impact_unit_check" CHECK ("iq_recommendations"."impact_unit" IN ('paise', 'count', 'bps', 'grams', 'ml', 'pieces', 'seconds')),
	CONSTRAINT "iq_recommendations_impact_range_check" CHECK ("iq_recommendations"."impact_low" <= "iq_recommendations"."impact_high"),
	CONSTRAINT "iq_recommendations_confidence_check" CHECK ("iq_recommendations"."confidence" IN ('LOW', 'MEDIUM', 'HIGH')),
	CONSTRAINT "iq_recommendations_assumptions_check" CHECK (jsonb_typeof("iq_recommendations"."assumptions") = 'array' AND jsonb_array_length("iq_recommendations"."assumptions") >= 1),
	CONSTRAINT "iq_recommendations_status_check" CHECK ("iq_recommendations"."status" IN ('PROPOSED', 'APPROVED', 'DISMISSED', 'EXPIRED', 'SUPERSEDED')),
	CONSTRAINT "iq_recommendations_decided_check" CHECK (("iq_recommendations"."status" = 'PROPOSED') = ("iq_recommendations"."decided_at" IS NULL)),
	CONSTRAINT "iq_recommendations_decided_by_check" CHECK ("iq_recommendations"."status" NOT IN ('APPROVED', 'DISMISSED') OR "iq_recommendations"."decided_by_user_id" IS NOT NULL),
	CONSTRAINT "iq_recommendations_reason_check" CHECK (char_length("iq_recommendations"."decision_reason") <= 500)
);
--> statement-breakpoint
ALTER TABLE "iq_actions" ADD CONSTRAINT "iq_actions_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_actions" ADD CONSTRAINT "iq_actions_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_actions" ADD CONSTRAINT "iq_actions_audit_log_id_audit_logs_id_fk" FOREIGN KEY ("audit_log_id") REFERENCES "public"."audit_logs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_actions" ADD CONSTRAINT "iq_actions_job_run_id_iq_job_runs_id_fk" FOREIGN KEY ("job_run_id") REFERENCES "public"."iq_job_runs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_actions" ADD CONSTRAINT "iq_actions_recommendation_fk" FOREIGN KEY ("recommendation_id","org_id") REFERENCES "public"."iq_recommendations"("id","org_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_actions" ADD CONSTRAINT "iq_actions_auto_policy_fk" FOREIGN KEY ("auto_policy_id","org_id") REFERENCES "public"."iq_auto_policies"("id","org_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_auto_policies" ADD CONSTRAINT "iq_auto_policies_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_auto_policies" ADD CONSTRAINT "iq_auto_policies_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_auto_policies" ADD CONSTRAINT "iq_auto_policies_audit_log_id_audit_logs_id_fk" FOREIGN KEY ("audit_log_id") REFERENCES "public"."audit_logs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_forecasts" ADD CONSTRAINT "iq_forecasts_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_forecasts" ADD CONSTRAINT "iq_forecasts_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_forecasts" ADD CONSTRAINT "iq_forecasts_insight_id_iq_insights_id_fk" FOREIGN KEY ("insight_id") REFERENCES "public"."iq_insights"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_forecasts" ADD CONSTRAINT "iq_forecasts_job_run_id_iq_job_runs_id_fk" FOREIGN KEY ("job_run_id") REFERENCES "public"."iq_job_runs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_insights" ADD CONSTRAINT "iq_insights_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_insights" ADD CONSTRAINT "iq_insights_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_insights" ADD CONSTRAINT "iq_insights_job_run_id_iq_job_runs_id_fk" FOREIGN KEY ("job_run_id") REFERENCES "public"."iq_job_runs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_insights" ADD CONSTRAINT "iq_insights_supersedes_fk" FOREIGN KEY ("supersedes") REFERENCES "public"."iq_insights"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_insights" ADD CONSTRAINT "iq_insights_superseded_by_fk" FOREIGN KEY ("superseded_by") REFERENCES "public"."iq_insights"("id") ON DELETE set null ON UPDATE no action DEFERRABLE INITIALLY DEFERRED;--> statement-breakpoint
ALTER TABLE "iq_job_runs" ADD CONSTRAINT "iq_job_runs_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_outcomes" ADD CONSTRAINT "iq_outcomes_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_outcomes" ADD CONSTRAINT "iq_outcomes_job_run_id_iq_job_runs_id_fk" FOREIGN KEY ("job_run_id") REFERENCES "public"."iq_job_runs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_recommendations" ADD CONSTRAINT "iq_recommendations_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_recommendations" ADD CONSTRAINT "iq_recommendations_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_recommendations" ADD CONSTRAINT "iq_recommendations_insight_fk" FOREIGN KEY ("insight_id","org_id") REFERENCES "public"."iq_insights"("id","org_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "iq_actions_org_status_created_idx" ON "iq_actions" USING btree ("org_id","status","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "iq_actions_pending_idx" ON "iq_actions" USING btree ("org_id","approval_expires_at") WHERE "iq_actions"."status" = 'PENDING_APPROVAL';--> statement-breakpoint
CREATE INDEX "iq_actions_recommendation_idx" ON "iq_actions" USING btree ("recommendation_id");--> statement-breakpoint
CREATE UNIQUE INDEX "iq_actions_open_params_unique" ON "iq_actions" USING btree ("org_id","action_kind","params_hash") WHERE "iq_actions"."status" IN ('QUEUED', 'PENDING_APPROVAL', 'APPROVED', 'EXECUTING', 'HANDOFF');--> statement-breakpoint
CREATE INDEX "iq_actions_cooldown_idx" ON "iq_actions" USING btree ("org_id","action_kind","params_hash","status_changed_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "iq_actions_auto_usage_idx" ON "iq_actions" USING btree ("org_id","action_kind","location_id","created_at") WHERE "iq_actions"."mode" = 'AUTO';--> statement-breakpoint
CREATE INDEX "iq_actions_stale_lease_idx" ON "iq_actions" USING btree ("lease_expires_at") WHERE "iq_actions"."status" IN ('EXECUTING', 'UNDOING');--> statement-breakpoint
CREATE INDEX "iq_forecasts_insight_idx" ON "iq_forecasts" USING btree ("insight_id");--> statement-breakpoint
CREATE INDEX "iq_forecasts_job_run_idx" ON "iq_forecasts" USING btree ("job_run_id");--> statement-breakpoint
CREATE UNIQUE INDEX "iq_insights_active_dedupe_unique" ON "iq_insights" USING btree ("org_id","dedupe_key") WHERE "iq_insights"."status" = 'ACTIVE';--> statement-breakpoint
CREATE INDEX "iq_insights_org_claim_created_idx" ON "iq_insights" USING btree ("org_id","claim_type","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "iq_insights_org_subject_idx" ON "iq_insights" USING btree ("org_id","subject_kind","subject_ref");--> statement-breakpoint
CREATE INDEX "iq_insights_job_run_idx" ON "iq_insights" USING btree ("job_run_id");--> statement-breakpoint
CREATE INDEX "iq_job_runs_org_job_started_idx" ON "iq_job_runs" USING btree ("org_id","job","started_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "iq_job_runs_open_lease_idx" ON "iq_job_runs" USING btree ("status","lease_expires_at") WHERE "iq_job_runs"."status" IN ('RUNNING', 'FAILED');--> statement-breakpoint
CREATE INDEX "iq_outcomes_job_run_idx" ON "iq_outcomes" USING btree ("job_run_id");--> statement-breakpoint
CREATE UNIQUE INDEX "iq_recommendations_proposed_dedupe_unique" ON "iq_recommendations" USING btree ("org_id","dedupe_key") WHERE "iq_recommendations"."status" = 'PROPOSED';--> statement-breakpoint
CREATE INDEX "iq_recommendations_cooldown_idx" ON "iq_recommendations" USING btree ("org_id","action_kind","params_hash","decided_at" DESC NULLS LAST);

--> statement-breakpoint
-- A referenced insight is frozen. Once a recommendation cites an insight —
-- as its own RECOMMENDATION row or through payload.evidenceInsightIds — what
-- it claimed cannot be rewritten underneath the decision; a changed claim is
-- a new row that supersedes it. status, superseded_by and expires_at stay
-- writable so that superseding and expiry still work.
CREATE FUNCTION public.iq_insights_freeze_referenced()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF OLD.referenced_at IS NOT NULL AND (
       NEW.referenced_at IS DISTINCT FROM OLD.referenced_at
    OR NEW.org_id IS DISTINCT FROM OLD.org_id
    OR NEW.location_id IS DISTINCT FROM OLD.location_id
    OR NEW.claim_type IS DISTINCT FROM OLD.claim_type
    OR NEW.schema_version IS DISTINCT FROM OLD.schema_version
    OR NEW.subject_kind IS DISTINCT FROM OLD.subject_kind
    OR NEW.subject_ref IS DISTINCT FROM OLD.subject_ref
    OR NEW.period_start IS DISTINCT FROM OLD.period_start
    OR NEW.period_end IS DISTINCT FROM OLD.period_end
    OR NEW.dedupe_key IS DISTINCT FROM OLD.dedupe_key
    OR NEW.payload IS DISTINCT FROM OLD.payload
    OR NEW.evidence IS DISTINCT FROM OLD.evidence
    OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
  ) THEN
    RAISE EXCEPTION 'iq_insights %: referenced insights are frozen; supersede with a new row', OLD.id
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END;
$$;
--> statement-breakpoint
CREATE TRIGGER iq_insights_freeze_referenced_trigger
BEFORE UPDATE ON public.iq_insights
FOR EACH ROW EXECUTE FUNCTION public.iq_insights_freeze_referenced();
--> statement-breakpoint
-- Marks the cited insights referenced in the same transaction as the
-- recommendation, so no repository can forget to. The recommendation's own
-- insight must be a RECOMMENDATION claim; its evidence ids are frozen too,
-- within the same org only.
CREATE FUNCTION public.iq_recommendations_reference_insights()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  claim text;
  cited jsonb;
BEGIN
  SELECT claim_type, payload -> 'evidenceInsightIds' INTO claim, cited
  FROM iq_insights
  WHERE id = NEW.insight_id AND org_id = NEW.org_id;

  IF claim IS DISTINCT FROM 'RECOMMENDATION' THEN
    RAISE EXCEPTION 'iq_recommendations %: insight % is not a RECOMMENDATION of this org', NEW.id, NEW.insight_id
      USING ERRCODE = '23514';
  END IF;

  UPDATE iq_insights
  SET referenced_at = now()
  WHERE org_id = NEW.org_id
    AND referenced_at IS NULL
    AND (
      id = NEW.insight_id
      OR (jsonb_typeof(cited) = 'array'
          AND id::text IN (SELECT jsonb_array_elements_text(cited)))
    );
  RETURN NEW;
END;
$$;
--> statement-breakpoint
CREATE TRIGGER iq_recommendations_reference_insights_trigger
AFTER INSERT OR UPDATE OF insight_id ON public.iq_recommendations
FOR EACH ROW EXECUTE FUNCTION public.iq_recommendations_reference_insights();
--> statement-breakpoint
-- iq_actions.status_changed_at is database time, never the caller's clock
-- (RELIABILITY C6): the cooldown and stale-row sweeps read it.
CREATE FUNCTION public.iq_actions_stamp_status_change()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' OR NEW.status IS DISTINCT FROM OLD.status THEN
    NEW.status_changed_at := now();
  ELSE
    NEW.status_changed_at := OLD.status_changed_at;
  END IF;
  RETURN NEW;
END;
$$;
--> statement-breakpoint
CREATE TRIGGER iq_actions_stamp_status_change_trigger
BEFORE INSERT OR UPDATE ON public.iq_actions
FOR EACH ROW EXECUTE FUNCTION public.iq_actions_stamp_status_change();
--> statement-breakpoint
-- RLS and grants. 0033 stopped anon/authenticated getting INSERT, UPDATE,
-- DELETE and TRUNCATE on new tables, but Supabase's defaults still hand them
-- SELECT, REFERENCES and TRIGGER — so every iq_* table starts from REVOKE ALL.
-- Staff (OWNER, ADMIN, MANAGER) may read insights, recommendations and
-- actions of their own org; the rest are server-only: RLS on, no policy, no
-- grant. Nothing is writable except by postgres (the app), which bypasses RLS.
DO $$
DECLARE
  target text;
BEGIN
  FOREACH target IN ARRAY ARRAY[
    'iq_job_runs', 'iq_insights', 'iq_forecasts', 'iq_recommendations',
    'iq_actions', 'iq_outcomes', 'iq_auto_policies'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', target);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', target);
    EXECUTE format('REVOKE ALL ON TABLE %I FROM PUBLIC, anon, authenticated', target);
  END LOOP;

  FOREACH target IN ARRAY ARRAY['iq_insights', 'iq_recommendations', 'iq_actions'] LOOP
    EXECUTE format(
      'CREATE POLICY %I ON %I FOR SELECT TO authenticated
         USING (auth_has_role(org_id, ARRAY[''OWNER'', ''ADMIN'', ''MANAGER'']))',
      target || '_staff_read', target
    );
    EXECUTE format('GRANT SELECT ON TABLE %I TO authenticated', target);
  END LOOP;
END $$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION public.iq_insights_freeze_referenced() FROM PUBLIC, anon, authenticated;
--> statement-breakpoint
REVOKE ALL ON FUNCTION public.iq_recommendations_reference_insights() FROM PUBLIC, anon, authenticated;
--> statement-breakpoint
REVOKE ALL ON FUNCTION public.iq_actions_stamp_status_change() FROM PUBLIC, anon, authenticated;
