-- IQ-1 facts: iq_daily_facts, iq_intraday_facts, iq_daily_trust, plus the
-- read-path indexes the fact jobs need. Requires 0034 (iq_job_runs) and 0035.
-- hive reviews/iq-1 DESIGN.md "Tables", REVIEW.md B1-B7, P1, P4; schema in
-- src/db/schema/iq-facts.ts. Recovery: docs/MIGRATION-RECOVERY.md §4c and
-- supabase/rollback/0036_iq_facts.down.sql.
--
-- Generated by drizzle-kit; RLS and grants are hand-written at the end.
-- The three indexes on orders, payments and inventory_movements are plain
-- CREATE INDEX (Drizzle runs every migration in one transaction, so not
-- CONCURRENTLY): each briefly blocks writes to its table while it builds.
--
-- Journal `when` set by hand to 1790000000000 (above 0035's 1789900000000);
-- drizzle-kit's wall-clock stamp would be skipped by `db:migrate`.
CREATE TABLE "iq_daily_facts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"location_id" uuid,
	"business_date" date NOT NULL,
	"metric_id" text NOT NULL,
	"dimension_key" text DEFAULT '' NOT NULL,
	"dimension_value" text DEFAULT '' NOT NULL,
	"unit" text NOT NULL,
	"value" bigint NOT NULL,
	"source_row_count" integer DEFAULT 0 NOT NULL,
	"source_watermark" timestamp with time zone,
	"definition_version" integer NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"job_run_id" uuid,
	CONSTRAINT "iq_daily_facts_key_unique" UNIQUE NULLS NOT DISTINCT("org_id","location_id","business_date","metric_id","dimension_key","dimension_value","definition_version"),
	CONSTRAINT "iq_daily_facts_metric_id_check" CHECK ("iq_daily_facts"."metric_id" ~ '^[a-z][a-z0-9_]{0,63}$'),
	CONSTRAINT "iq_daily_facts_dimension_check" CHECK (("iq_daily_facts"."dimension_key" = '' AND "iq_daily_facts"."dimension_value" = '')
        OR ("iq_daily_facts"."dimension_key" ~ '^[a-z][a-z0-9_]{0,63}$' AND char_length("iq_daily_facts"."dimension_value") BETWEEN 1 AND 200)),
	CONSTRAINT "iq_daily_facts_unit_check" CHECK ("iq_daily_facts"."unit" IN ('paise', 'count')),
	CONSTRAINT "iq_daily_facts_source_row_count_check" CHECK ("iq_daily_facts"."source_row_count" >= 0),
	CONSTRAINT "iq_daily_facts_definition_version_check" CHECK ("iq_daily_facts"."definition_version" >= 1)
);
--> statement-breakpoint
CREATE TABLE "iq_daily_trust" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"location_id" uuid,
	"business_date" date NOT NULL,
	"signal_id" text NOT NULL,
	"numerator" bigint DEFAULT 0 NOT NULL,
	"denominator" bigint DEFAULT 0 NOT NULL,
	"grade" text NOT NULL,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"definition_version" integer NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"job_run_id" uuid,
	CONSTRAINT "iq_daily_trust_key_unique" UNIQUE NULLS NOT DISTINCT("org_id","location_id","business_date","signal_id","definition_version"),
	CONSTRAINT "iq_daily_trust_signal_id_check" CHECK ("iq_daily_trust"."signal_id" ~ '^[a-z][a-z0-9_]{0,63}$'),
	CONSTRAINT "iq_daily_trust_grade_check" CHECK ("iq_daily_trust"."grade" IN ('HIGH', 'MEDIUM', 'LOW', 'UNKNOWN')),
	CONSTRAINT "iq_daily_trust_counts_check" CHECK ("iq_daily_trust"."numerator" >= 0 AND "iq_daily_trust"."denominator" >= 0),
	CONSTRAINT "iq_daily_trust_detail_check" CHECK (jsonb_typeof("iq_daily_trust"."detail") = 'object' AND NOT jsonb_path_exists("iq_daily_trust"."detail", '$.* ? (@.type() != "number")')),
	CONSTRAINT "iq_daily_trust_definition_version_check" CHECK ("iq_daily_trust"."definition_version" >= 1)
);
--> statement-breakpoint
CREATE TABLE "iq_intraday_facts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"location_id" uuid,
	"business_date" date NOT NULL,
	"metric_id" text NOT NULL,
	"dimension_key" text DEFAULT '' NOT NULL,
	"dimension_value" text DEFAULT '' NOT NULL,
	"unit" text NOT NULL,
	"value" bigint NOT NULL,
	"source_row_count" integer DEFAULT 0 NOT NULL,
	"source_watermark" timestamp with time zone,
	"definition_version" integer NOT NULL,
	"computed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"job_run_id" uuid,
	"bucket_start" timestamp with time zone NOT NULL,
	CONSTRAINT "iq_intraday_facts_key_unique" UNIQUE NULLS NOT DISTINCT("org_id","location_id","bucket_start","metric_id","dimension_key","dimension_value","definition_version"),
	CONSTRAINT "iq_intraday_facts_metric_id_check" CHECK ("iq_intraday_facts"."metric_id" ~ '^[a-z][a-z0-9_]{0,63}$'),
	CONSTRAINT "iq_intraday_facts_dimension_check" CHECK (("iq_intraday_facts"."dimension_key" = '' AND "iq_intraday_facts"."dimension_value" = '')
        OR ("iq_intraday_facts"."dimension_key" ~ '^[a-z][a-z0-9_]{0,63}$' AND char_length("iq_intraday_facts"."dimension_value") BETWEEN 1 AND 200)),
	CONSTRAINT "iq_intraday_facts_unit_check" CHECK ("iq_intraday_facts"."unit" IN ('paise', 'count')),
	CONSTRAINT "iq_intraday_facts_source_row_count_check" CHECK ("iq_intraday_facts"."source_row_count" >= 0),
	CONSTRAINT "iq_intraday_facts_definition_version_check" CHECK ("iq_intraday_facts"."definition_version" >= 1),
	CONSTRAINT "iq_intraday_facts_bucket_check" CHECK (extract(epoch FROM "iq_intraday_facts"."bucket_start")::bigint % 900 = 0),
	CONSTRAINT "iq_intraday_facts_bucket_day_check" CHECK (("iq_intraday_facts"."bucket_start" AT TIME ZONE 'Asia/Kolkata')::date = "iq_intraday_facts"."business_date")
);
--> statement-breakpoint
ALTER TABLE "iq_daily_facts" ADD CONSTRAINT "iq_daily_facts_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_daily_facts" ADD CONSTRAINT "iq_daily_facts_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_daily_facts" ADD CONSTRAINT "iq_daily_facts_job_run_id_iq_job_runs_id_fk" FOREIGN KEY ("job_run_id") REFERENCES "public"."iq_job_runs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_daily_trust" ADD CONSTRAINT "iq_daily_trust_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_daily_trust" ADD CONSTRAINT "iq_daily_trust_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_daily_trust" ADD CONSTRAINT "iq_daily_trust_job_run_id_iq_job_runs_id_fk" FOREIGN KEY ("job_run_id") REFERENCES "public"."iq_job_runs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_intraday_facts" ADD CONSTRAINT "iq_intraday_facts_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_intraday_facts" ADD CONSTRAINT "iq_intraday_facts_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "iq_intraday_facts" ADD CONSTRAINT "iq_intraday_facts_job_run_id_iq_job_runs_id_fk" FOREIGN KEY ("job_run_id") REFERENCES "public"."iq_job_runs"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "iq_daily_facts_org_date_idx" ON "iq_daily_facts" USING btree ("org_id","business_date");--> statement-breakpoint
CREATE INDEX "iq_daily_facts_org_metric_date_idx" ON "iq_daily_facts" USING btree ("org_id","metric_id","business_date");--> statement-breakpoint
CREATE INDEX "iq_daily_facts_job_run_idx" ON "iq_daily_facts" USING btree ("job_run_id");--> statement-breakpoint
CREATE INDEX "iq_daily_trust_org_date_idx" ON "iq_daily_trust" USING btree ("org_id","business_date");--> statement-breakpoint
CREATE INDEX "iq_daily_trust_job_run_idx" ON "iq_daily_trust" USING btree ("job_run_id");--> statement-breakpoint
CREATE INDEX "iq_intraday_facts_org_date_idx" ON "iq_intraday_facts" USING btree ("org_id","business_date");--> statement-breakpoint
CREATE INDEX "iq_intraday_facts_org_metric_bucket_idx" ON "iq_intraday_facts" USING btree ("org_id","metric_id","bucket_start");--> statement-breakpoint
CREATE INDEX "iq_intraday_facts_job_run_idx" ON "iq_intraday_facts" USING btree ("job_run_id");--> statement-breakpoint
CREATE INDEX "orders_org_created_idx" ON "orders" USING btree ("org_id","created_at");--> statement-breakpoint
CREATE INDEX "payments_order_captured_idx" ON "payments" USING btree ("order_id") WHERE "payments"."status" IN ('CAPTURED', 'PARTIALLY_REFUNDED');--> statement-breakpoint
CREATE INDEX "inventory_movements_org_type_occurred_idx" ON "inventory_movements" USING btree ("org_id","type","occurred_at");

--> statement-breakpoint
-- RLS and grants. Supabase's defaults still give anon/authenticated SELECT,
-- REFERENCES and TRIGGER on new tables (0033 revoked only writes), so each
-- table starts from REVOKE ALL. Reading through a Supabase key is limited to
-- OWNER and MANAGER of the row's org — the finance.view roles in
-- src/domain/permissions.ts — because these rows are revenue, food cost and
-- expense figures. The app reads and writes as postgres, which bypasses RLS,
-- and its repositories filter on org_id themselves.
DO $$
DECLARE
  target text;
BEGIN
  FOREACH target IN ARRAY ARRAY['iq_daily_facts', 'iq_intraday_facts', 'iq_daily_trust'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', target);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', target);
    EXECUTE format('REVOKE ALL ON TABLE %I FROM PUBLIC, anon, authenticated', target);
    EXECUTE format(
      'CREATE POLICY %I ON %I FOR SELECT TO authenticated
         USING (auth_has_role(org_id, ARRAY[''OWNER'', ''MANAGER'']))',
      target || '_finance_read', target
    );
    EXECUTE format('GRANT SELECT ON TABLE %I TO authenticated', target);
  END LOOP;
END $$;
