-- Day off and planned closures (ops-3): organizations.weekly_closed_days (the
-- weekdays the shop is closed all day, 0 = Sunday .. 6 = Saturday; empty = open
-- every day) and closed_dates (a date or a run of dates with an optional public
-- note). placeOrder, the picker, the banner and the staff pill all read them;
-- the trading hours themselves are untouched. Recovery: docs/MIGRATION-RECOVERY.md
-- §4g and supabase/rollback/0040_day_off.down.sql.
--
-- Expand-only, safe before the deploy: one column with a constant default (a
-- catalogue change on PG 11+, no table rewrite) and one new empty table. Every
-- existing org reads as "open every day, no closed dates", which is what the
-- code already live assumes. The Tuesday off day is NOT set here: it is a data
-- change made separately, on the owner's yes.
--
-- Generated by drizzle-kit; the lock timeout and the RLS block are hand-written.
-- Journal `when` set by hand to 1790500000000, above 0039's 1790400000000.
--
-- organizations is read on every request: give up after 5 s rather than queue
-- the whole site behind a long transaction.
SET LOCAL lock_timeout = '5s';--> statement-breakpoint
CREATE TABLE "closed_dates" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"public_note" text,
	"created_by" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "closed_dates_range_check" CHECK ("closed_dates"."end_date" >= "closed_dates"."start_date"),
	CONSTRAINT "closed_dates_note_check" CHECK ("closed_dates"."public_note" IS NULL OR char_length("closed_dates"."public_note") BETWEEN 1 AND 120)
);
--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "weekly_closed_days" smallint[] DEFAULT '{}'::smallint[] NOT NULL;--> statement-breakpoint
ALTER TABLE "closed_dates" ADD CONSTRAINT "closed_dates_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "closed_dates_org_end_idx" ON "closed_dates" USING btree ("org_id","end_date");--> statement-breakpoint
ALTER TABLE "organizations" ADD CONSTRAINT "organizations_weekly_closed_days_check" CHECK ("organizations"."weekly_closed_days" <@ ARRAY[0,1,2,3,4,5,6]::smallint[] AND cardinality("organizations"."weekly_closed_days") <= 6);
--> statement-breakpoint
-- Same posture as 0033/0036: RLS on and forced, no client DML for either API
-- role, members may read their own org's rows through a Supabase key. The app
-- itself writes as `postgres` through Drizzle.
ALTER TABLE "closed_dates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "closed_dates" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
REVOKE ALL ON TABLE "closed_dates" FROM PUBLIC, anon, authenticated;--> statement-breakpoint
CREATE POLICY closed_dates_tenant_read ON "closed_dates" FOR SELECT TO authenticated
  USING (org_id IN (SELECT auth_org_ids()));--> statement-breakpoint
GRANT SELECT ON TABLE "closed_dates" TO authenticated;
