-- The till (roadmap 5.1-5.3): cash_sessions (open with a float, close with a
-- counted amount, an expected amount worked out from rows, and the variance
-- against the person who closed it), cash_handovers (a rider hands door cash
-- into the open session, with the rider's declared amount against the books'),
-- and four nullable/defaulted columns on payments (cash_session_id,
-- collected_by, held_by_rider, handover_id). Recovery:
-- docs/MIGRATION-RECOVERY.md 4h and supabase/rollback/0041_cash_sessions.down.sql.
--
-- Expand-only, safe before the deploy: two new empty tables and four columns
-- on payments that the code already live never names (nullable, or a constant
-- default: catalogue-only on PG 11+, no rewrite). Every existing payment reads
-- as "not in any session, not held by a rider", which is what it was. The one
-- CHECK on payments is validated against a table of about a hundred rows.
--
-- Generated by drizzle-kit; the lock timeout and the RLS block are hand-written.
-- Journal `when` set by hand to 1790600000000, above 0040's 1790500000000.
--
-- payments is written on every sale: give up after 5 s rather than queue the
-- counter behind a long transaction.
SET LOCAL lock_timeout = '5s';--> statement-breakpoint
CREATE TABLE "cash_handovers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"session_id" uuid NOT NULL,
	"rider_user_id" uuid NOT NULL,
	"received_by" uuid NOT NULL,
	"expected_amount" bigint NOT NULL,
	"declared_amount" bigint NOT NULL,
	"variance" bigint NOT NULL,
	"payment_count" integer NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "cash_handovers_amounts_check" CHECK ("cash_handovers"."expected_amount" >= 0 AND "cash_handovers"."declared_amount" >= 0 AND "cash_handovers"."variance" = "cash_handovers"."declared_amount" - "cash_handovers"."expected_amount" AND "cash_handovers"."payment_count" >= 1),
	CONSTRAINT "cash_handovers_note_check" CHECK ("cash_handovers"."note" IS NULL OR char_length("cash_handovers"."note") BETWEEN 1 AND 200)
);
--> statement-breakpoint
CREATE TABLE "cash_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"org_id" uuid NOT NULL,
	"location_id" uuid NOT NULL,
	"status" text DEFAULT 'OPEN' NOT NULL,
	"opened_by" uuid NOT NULL,
	"opened_at" timestamp with time zone DEFAULT now() NOT NULL,
	"opening_float" bigint NOT NULL,
	"closed_by" uuid,
	"closed_at" timestamp with time zone,
	"counted_cash" bigint,
	"expected_cash" bigint,
	"variance" bigint,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "cash_sessions_status_check" CHECK ("cash_sessions"."status" IN ('OPEN', 'CLOSED')),
	CONSTRAINT "cash_sessions_float_check" CHECK ("cash_sessions"."opening_float" >= 0),
	CONSTRAINT "cash_sessions_closed_check" CHECK (("cash_sessions"."status" = 'OPEN' AND "cash_sessions"."closed_by" IS NULL AND "cash_sessions"."closed_at" IS NULL AND "cash_sessions"."counted_cash" IS NULL AND "cash_sessions"."expected_cash" IS NULL AND "cash_sessions"."variance" IS NULL)
        OR ("cash_sessions"."status" = 'CLOSED' AND "cash_sessions"."closed_by" IS NOT NULL AND "cash_sessions"."closed_at" IS NOT NULL AND "cash_sessions"."counted_cash" IS NOT NULL AND "cash_sessions"."expected_cash" IS NOT NULL AND "cash_sessions"."variance" IS NOT NULL AND "cash_sessions"."counted_cash" >= 0 AND "cash_sessions"."variance" = "cash_sessions"."counted_cash" - "cash_sessions"."expected_cash")),
	CONSTRAINT "cash_sessions_note_check" CHECK ("cash_sessions"."note" IS NULL OR char_length("cash_sessions"."note") BETWEEN 1 AND 200)
);
--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "cash_session_id" uuid;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "collected_by" uuid;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "held_by_rider" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "payments" ADD COLUMN "handover_id" uuid;--> statement-breakpoint
ALTER TABLE "cash_handovers" ADD CONSTRAINT "cash_handovers_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cash_handovers" ADD CONSTRAINT "cash_handovers_session_id_cash_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."cash_sessions"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cash_sessions" ADD CONSTRAINT "cash_sessions_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cash_sessions" ADD CONSTRAINT "cash_sessions_location_id_locations_id_fk" FOREIGN KEY ("location_id") REFERENCES "public"."locations"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "cash_handovers_org_created_idx" ON "cash_handovers" USING btree ("org_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "cash_sessions_one_open_idx" ON "cash_sessions" USING btree ("org_id","location_id") WHERE "cash_sessions"."status" = 'OPEN';--> statement-breakpoint
CREATE INDEX "cash_sessions_org_opened_idx" ON "cash_sessions" USING btree ("org_id","opened_at");--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_cash_session_id_cash_sessions_id_fk" FOREIGN KEY ("cash_session_id") REFERENCES "public"."cash_sessions"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_handover_id_cash_handovers_id_fk" FOREIGN KEY ("handover_id") REFERENCES "public"."cash_handovers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "payments_cash_session_idx" ON "payments" USING btree ("cash_session_id") WHERE "payments"."cash_session_id" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "payments_rider_unhanded_idx" ON "payments" USING btree ("org_id","collected_by") WHERE "payments"."held_by_rider" AND "payments"."handover_id" IS NULL;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_cash_holder_check" CHECK (("payments"."handover_id" IS NULL OR "payments"."held_by_rider") AND (NOT "payments"."held_by_rider" OR ("payments"."handover_id" IS NULL) = ("payments"."cash_session_id" IS NULL)));
--> statement-breakpoint
-- Same posture as 0033/0036/0040: RLS on and forced, no client DML for either
-- API role, members may read their own org's rows through a Supabase key. The
-- app writes as `postgres` through Drizzle. Reading the till is finance.view in
-- the app; these policies only bound a Supabase key to its own org.
ALTER TABLE "cash_sessions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "cash_sessions" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "cash_handovers" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "cash_handovers" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
REVOKE ALL ON TABLE "cash_sessions", "cash_handovers" FROM PUBLIC, anon, authenticated;--> statement-breakpoint
CREATE POLICY cash_sessions_tenant_read ON "cash_sessions" FOR SELECT TO authenticated
  USING (org_id IN (SELECT auth_org_ids()));--> statement-breakpoint
CREATE POLICY cash_handovers_tenant_read ON "cash_handovers" FOR SELECT TO authenticated
  USING (org_id IN (SELECT auth_org_ids()));--> statement-breakpoint
GRANT SELECT ON TABLE "cash_sessions", "cash_handovers" TO authenticated;
